name: Integration Tests

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - db_name: MySQL
            db_image: mysql:8.4
            health_cmd: mysqladmin ping -h 127.0.0.1 -uroot -ppassword --silent
          - db_name: MariaDB
            db_image: mariadb:11.4
            health_cmd: mariadb-admin ping -h 127.0.0.1 -uroot -ppassword --silent
    services:
      db:
        image: ${{ matrix.db_image }}
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: "%"
          MARIADB_ROOT_PASSWORD: password
          MARIADB_ROOT_HOST: "%"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="${{ matrix.health_cmd }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=12
    steps:
      - uses: actions/checkout@v4
      - name: Install zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Run Integration Tests - ${{ matrix.db_name }}
        run: |
          zig build
          zig build integration_test --summary all
